### ISSUE TITLE
Cross-Site Scripting on First and Last name Fields

### ISSUE THREAD

**Issue by atoooooooooom10** [vikingco/django-advanced-reports#42]
Hello there,

I just entered to your demo site and tested if there's a vulnerability and I found a cross-site scripting on first and last name fields.
I tried to input ``` "><img src=x onerror=alert(document.domain)> ``` but it was restricted because the maximum length of first and last name input field is 30 and my xss payload has 44 characters.
So, I changed my xss payload to ``` "><img src=x onerror=alert(1)> ``` and it works.
Screenshot:
![XSS](http://i.imgur.com/tlusbEG.png)

I already remove the xss and put back the default values.

**Comment by atoooooooooom10** [comment]
I found another one.
The Say hello modal executes an XSS code
![Say Hello XSS](http://i.imgur.com/BJfHEej.png)

**Comment by jgeskens** [comment]
Fixed: https://github.com/vikingco/django-advanced-reports/commit/c6dd50230017654b7d46f5fb954b1eae65b98f9d

**Comment by atoooooooooom10** [comment]
Nice! I have confirmed the bug no longer reproduces for me.

**Comment by jgeskens** [comment]
Do you participate in the HackerOne program for Mobile Vikings? Let me know if this is the case.

**Comment by atoooooooooom10** [comment]
Yes, I'm a participant from HackerOne and I already reported two vulnerability that I found on Mobile Vikings.
Report [#48046](https://hackerone.com/reports/48046)	 and Report [#48054](https://hackerone.com/reports/48054)

**Comment by jgeskens** [comment]
OK, great! Just checking :-)

Then I can close this ticket now.
